appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Gpt6AxCwR3ux01BGlHhiPw8YVdp1e1/ed4gh0GZPCgMFDDXf/HQmZHgpYm3Z97ppM6zP/YQJqyHf8SwBF4Krr77D294ra6HpYSSKWZeDZvwuwlpkWEYMGOjKl4pXYkyUby+L3RHy/63XEkAcVY1zhynIYfZ0Wj9c8nVdeAEVBXWg6vZPGyVwrbOiSQIWV4jJcejePT8gzR9hjhn4huauRCwJLi5TLx8ljAUYP6B7IgFsFN4vnAzdCw9415cCDRpyXkI3DaZ3mgKA4kSdb/rrQR4lAl5GPPGzPEf1x7yoTg3XcB0uB6G/sqHT3P3STWngVhXhssdF8aKSIO8xe8MfhosOFNj4/L4hHwspN0JpgyOvYvHRrkI9LFBPN0Bxx5a1qsXaiTb3OL1Hv15oa5MhF4kunSN/tnY0dXB8rJulw1N0ZcWvI8BHFCp//6TLSxot30jRXd2YQo+46oygMfvF9HktvXkXop/Nv3H0atLvW7kMaYsWMbqMjv3r6qfesFGzwXcmSsAAoepkYuD343j0i+AtNyIW5nG+sOaR0FaUdRViRrqnflMLi0oegl8lZaR4kH43Y92+kHTnITUAK26WYX+wA5WAdCMDm1Y+Q+47QoadvQZYlvQlpsUKvlfVgVJeRi3N9P7h4GGdiWlTedX4ixKw7RBHrc+ET1MVv1/lL9k=}
