travis:
  secure:
    BINSTAR_TOKEN: aJaUuPqAOlgYrW55YfoB4oGYeLrKkdrDOktNJWfRsLfO+vuqlUi3NbVi3RMoLfTZWcBzl+TKlRdR1z6nipJTzOBGWrM7AzvTeoRChtdbuPZ+f4s7SINgc42Y8/1VJmXEm/WR1vGDwfrN0tRP9kaBLhic0oT8KxcHNhMGTHqwBMSr0uimnKXMLiiTFtERarNK7n0aWSFbWs4dAU6skHScgbIlnwyNdPDLyKl77dJgIbfgMzhmaLdNG8XhEUwn0NPX03SAxCIptLcfxvuR6dzKNXNxGIe0JYF8Ne7VKJd/Igsdaiw29r9O5kC5FjEsrvbnFwAY0Bfa/ZTpQVMkjiTC0XlYHhWPiX2sDqU4Dpnx8gW5cm12Zc6p8j44B9iuSupx2CfAyfW/iyIwZu665qvUe8Vg/glkT+U4yrZNWaTCPZcyORY7lmlOkTfL9s94bpvBcKELuWhAot9v48Wzwst9QjYi9laydvvztGGEQiv2NtnlwPGs/1+DeAZ7Z+V0Jz8ok1/BafKCBwdR+mOdM+RJsJ3a37Ph1/v36Lss04UjQej+Uv3hTxxZC2G6yctcjavKUcN3EBiA9etEwbPy0EhS54D/LdJp02IdjyNYl4mq+N1u07+EjeV2kMSwdwJvXtyL5Z310We2WVbI1G2wZWCK/BqO8+uNLPsbpIOrioJtGlE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
